# Generated by Django 5.2.7 on 2025-10-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodict_name',
            new_name='product_name',
        ),
    ]
