# Generated by Django 5.2.7 on 2025-10-24 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
