# Generated by Django 5.2.7 on 2025-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_created_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
